### ISSUE TITLE
Request to share framework and the dataset used in the experiment

### ISSUE THREAD

**Issue by yyh-sjtu** [panjingyu/Robustify-ML-Based-Lithography-Hotspot-Detectors#1]
Dear panjingyu:
  You said that 'In order to contribute to the reproducibility and fair comparison in ML for CAD,
the framework and the dataset used in our experiment are anonymously open-sourced at https://github.com/panjingyu/Robustify-ML-Based-Lithography-Hotspot-Detectors.' Can you share the framework and the dataset with us?

**Comment by panjingyu** [comment]
Hi yyh-sjtu, many thanks for following this work! I have updated the code and the dataset link. Please let me know if you have any other questions.

**Comment by yyh-sjtu** [comment]
Thank you very much for replying me and sharing your work with us. I am a first-year graduate student majoring in CAD of IC & EDA, and I am very lucky to have access to your paper in ICCAD. I will learn about it carefully. Maybe I will have some questions later. Thank you again.

**Comment by yyh-sjtu** [comment]
> 



> Hi yyh-sjtu, many thanks for following this work! I have updated the code and the dataset link. Please let me know if you have any other questions.
Thank you very much for replying me and sharing your work with us. I am a first-year graduate student majoring in CAD of IC & EDA, and I am very lucky to have access to your paper in ICCAD. I will learn about it carefully. Maybe I will have some questions later. Thank you again.
